/**
 * WebViewFieldBridge — renders a web-only Payload component inside a WebView
 * with bidirectional data bridging to the native app and local-db.
 *
 * Used as a fallback when the codegen AST transform cannot translate a
 * component (e.g. it uses canvas, document.*, third-party web-only libs).
 *
 * Data flow:
 *   Native → WebView:  INIT, VALUE_UPDATE messages via postMessage
 *   WebView → Native:  FIELD_CHANGE, READY, LOCAL_QUERY, LOCAL_MUTATION
 *
 * Local-first: The WebView never hits the server directly. Data requests
 * are routed through the native side which queries local RxDB/SQLite.
 */
import React, { useCallback, useEffect, useRef, useState } from 'react'
import { StyleSheet, Text, View } from 'react-native'
import { WebView as RNWebView } from 'react-native-webview'
import { defaultTheme as t } from './theme'
import type { ClientField, FieldValue } from './types'

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface WebViewFieldBridgeProps {
  /** The field schema definition. */
  field: ClientField
  /** Current field value. */
  value: FieldValue
  /** Called when the WebView component changes the field value. */
  onChange: (value: FieldValue) => void
  /** Dot-path to the field in the form. */
  path: string
  /** Whether the field is disabled. */
  disabled?: boolean
  /** Validation error message. */
  error?: string
  /** Name of the component (for display in placeholder). */
  componentName?: string
  /** HTML content to render in the WebView. Generated by codegen. */
  htmlContent?: string
  /** URI to a local HTML file asset. */
  htmlUri?: string
  /** Minimum height for the WebView. */
  minHeight?: number
  /** Called when the WebView requests a local-db query. */
  onLocalQuery?: (slug: string, query: any) => Promise<any[]>
  /** Called when the WebView requests a local-db mutation. */
  onLocalMutation?: (slug: string, operation: string, data: any) => Promise<boolean>
  /** Inject the WebView component — avoids hard require on react-native-webview. */
  webViewComponent?: React.ComponentType<any>
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export const WebViewFieldBridge: React.FC<WebViewFieldBridgeProps> = ({
  field,
  value,
  onChange,
  path,
  disabled,
  error,
  componentName,
  htmlContent,
  htmlUri,
  minHeight = 100,
  onLocalQuery,
  onLocalMutation,
  webViewComponent: WebViewProp,
}) => {
  const webViewRef = useRef<any>(null)
  const [height, setHeight] = useState(minHeight)
  const [ready, setReady] = useState(false)

  // Send message to WebView
  const postToWebView = useCallback((msg: Record<string, any>) => {
    if (webViewRef.current && ready) {
      webViewRef.current.postMessage(JSON.stringify(msg))
    }
  }, [ready])

  // Send initial data when WebView is ready
  useEffect(() => {
    if (ready) {
      postToWebView({
        type: 'INIT',
        payload: { field, value, path, formData: {} },
      })
    }
  }, [ready, field, path]) // eslint-disable-line react-hooks/exhaustive-deps

  // Send value updates
  useEffect(() => {
    if (ready) {
      postToWebView({ type: 'VALUE_UPDATE', payload: { value } })
    }
  }, [value, ready, postToWebView])

  // Handle messages from WebView
  const handleMessage = useCallback(async (event: any) => {
    try {
      const msg = JSON.parse(event.nativeEvent.data)

      switch (msg.type) {
        case 'READY':
          setReady(true)
          break

        case 'FIELD_CHANGE':
          onChange(msg.payload.value)
          break

        case 'RESIZE':
          setHeight(Math.max(msg.payload.height, minHeight))
          break

        case 'LOCAL_QUERY':
          if (onLocalQuery) {
            const docs = await onLocalQuery(msg.payload.slug, msg.payload.query)
            postToWebView({
              type: 'LOCAL_QUERY_RESPONSE',
              payload: { requestId: msg.payload.requestId, docs },
            })
          }
          break

        case 'LOCAL_MUTATION':
          if (onLocalMutation) {
            const success = await onLocalMutation(
              msg.payload.slug,
              msg.payload.operation,
              msg.payload.data,
            )
            postToWebView({
              type: 'LOCAL_MUTATION_RESPONSE',
              payload: { requestId: msg.payload.requestId, success },
            })
          }
          break

        case 'ERROR':
          console.warn('[WebViewFieldBridge]', msg.payload.message)
          break
      }
    } catch (err) {
      console.warn('[WebViewFieldBridge] Failed to parse message:', err)
    }
  }, [onChange, onLocalQuery, onLocalMutation, minHeight, postToWebView])

  // Auto-resize script injected into the WebView
  const autoResizeScript = `
    (function() {
      function reportHeight() {
        var h = document.documentElement.scrollHeight || document.body.scrollHeight;
        window.ReactNativeWebView.postMessage(JSON.stringify({
          type: 'RESIZE', payload: { height: h }
        }));
      }
      if (typeof ResizeObserver !== 'undefined') {
        new ResizeObserver(reportHeight).observe(document.body);
      }
      reportHeight();
      window.ReactNativeWebView.postMessage(JSON.stringify({ type: 'READY' }));
    })();
    true;
  `

  const WebView = WebViewProp ?? RNWebView

  // If WebView is not available, show placeholder
  if (!WebView) {
    const name = componentName ?? field.name ?? 'Unknown'
    return (
      <View style={styles.placeholder}>
        <Text style={styles.placeholderTitle}>
          Custom Component: {name}
        </Text>
        <Text style={styles.placeholderText}>
          This field uses a web-only component.{'\n'}
          Edit on the web admin panel, or install{'\n'}
          react-native-webview for WebView fallback.
        </Text>
        {error && <Text style={styles.error}>{error}</Text>}
      </View>
    )
  }

  const source = htmlContent
    ? { html: htmlContent }
    : htmlUri
      ? { uri: htmlUri }
      : { html: generateFallbackHTML(field, componentName) }

  return (
    <View style={[styles.container, { minHeight: height }]}>
      <WebView
        ref={webViewRef}
        source={source}
        onMessage={handleMessage}
        injectedJavaScript={autoResizeScript}
        scrollEnabled={false}
        style={[styles.webview, { height }]}
        originWhitelist={['*']}
        javaScriptEnabled
        domStorageEnabled={false}
      />
      {error && <Text style={styles.error}>{error}</Text>}
    </View>
  )
}

// ---------------------------------------------------------------------------
// Fallback HTML
// ---------------------------------------------------------------------------

function generateFallbackHTML(field: ClientField, componentName?: string): string {
  const name = componentName ?? field.name ?? 'Unknown'
  return `<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body { font-family: -apple-system, system-ui, sans-serif; padding: 16px; margin: 0; color: #333; }
    .placeholder { text-align: center; padding: 24px; background: #f5f5f5; border-radius: 8px; }
    .title { font-weight: 600; margin-bottom: 8px; }
    .hint { color: #999; font-size: 13px; }
  </style>
</head>
<body>
  <div class="placeholder">
    <div class="title">Custom Component: ${name}</div>
    <div class="hint">Web-only component with WebView bridge active</div>
  </div>
  <script>
    window.ReactNativeWebView.postMessage(JSON.stringify({ type: 'READY' }));
  </script>
</body>
</html>`
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  container: {
    overflow: 'hidden',
    borderRadius: t.borderRadius.sm,
    marginVertical: t.spacing.xs,
  },
  webview: {
    backgroundColor: 'transparent',
  },
  placeholder: {
    padding: t.spacing.lg,
    backgroundColor: '#f5f5f5',
    borderRadius: t.borderRadius.sm,
    marginVertical: t.spacing.xs,
    alignItems: 'center',
  },
  placeholderTitle: {
    fontSize: t.fontSize.md,
    fontWeight: '600',
    color: t.colors.textMuted,
    marginBottom: t.spacing.xs,
  },
  placeholderText: {
    fontSize: t.fontSize.sm,
    color: t.colors.textPlaceholder,
    textAlign: 'center',
    lineHeight: 20,
  },
  error: {
    fontSize: 12,
    color: t.colors.error,
    marginTop: 3,
  },
})
